---
# set default to 1 to immediately publish articles by default or 0 to require approval
default: false

# rules to override the default
override:

  # override and publish, these rules are not checked if the default is 1
  publish:
    # keys are properties in EIF json, values are patterns to match against an articles value of that property
    # if any pattern matches the article will be publised immediately, regardless of default setting
    doi:
      - 00353$
    article-type:
      - research-article$

  # override and hold, these rules are not checked if the default is 0
  hold:
    # keys are properties in EIF json, values are patterns to match against an articles value of that property
    # if any pattern matches the article will be publised immediately, regardless of default setting
    doi:
      - 00001$
      - 00288$

# this specifically matches against the end of the DOI, set a date and time to automatically publish content
# overrides any default or matching override rules from above
schedule:
   - 00353: 01/04/2015 12:01
   - 00999: 25/12/1015 00:00










